defaults:
  - dataset: train
  - _self_ # keep this to the end of defaults to have config.yaml override values set in other yamls

### add global default parameter values below
dataset:
  # metadata source directory
  # mdata_src: '/home/sebalzer/Documents/Mike_init/Final_Regional_Database.xlsx'
  mdata_src: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/Final_Regional_Database.xlsx'
  # whether to save intermediate steps
  save_intermediate: False
  # whether to save the final pre-processed tables (only relevant if save_intermediate is False)
  save_final: True
  # which data to include in the pre-processing/analysis
  dims: ['2d']

analysis:
  # which segments to use data from (global, aha or roi)
  segments: ['roi']
  # which axes to consider
  axes: ['long_axis', 'short_axis']
  # which orientations to consider
  orientations: ['radial', 'circumf', 'longit']
  # which metrics to consider
  metrics: ['strain']
  # whether to reduce data to peak values (i.e. lose time component)
  peak_values: True
  # which metadata to include
  metadata: ['sex_0_male_1_female', 'age', 'bmi', 'mace', 'macefree_time', 'lv_ef']
  # experiment name (i.e. file name in which to store merged data)
  experiment: 'layer_analysis'
  # whether to overwrite merged data
  overwrite: False
  # whether to overwrite metadata 
  # (without performing entire merging process again - unless overwrite=True)
  update_metadata: False
  # which types of data exploration to perform (if any)
  exploration: ['univariate_analysis']
  # whether to remove outliers
  remove_outliers: False 
  # whether to investigate outliers
  investigate_outliers: False
  # determines reach of the whiskers in box plots and the range for outlier detection
  whis: 1