defaults:
  - dataset: train
  - _self_ # keep this to the end of defaults to have config.yaml override values set in other yamls

### add global default parameter values below
dataset:
  # whether to save intermediate steps
  save_intermediate: True
  # whether to save the final pre-processed tables (only relevant if save_intermediate is False)
  save_final: True
  # which data to include in the pre-processing/analysis
  dims: ['2d']

analysis:
  # which segments to use data from (global, aha or roi)
  segments: ['roi']
  # which axes to consider
  axes: ['long_axis', 'short_axis']
  # which orientations to consider
  orientations: ['radial', 'circumf', 'longit']
  # which metrics to consider
  metrics: ['strain', 'strain_rate']
  # whether to reduce data to peak values (i.e. lose time component)
  peak_values: True
