defaults:
  - dataset: train
  - _self_ # keep this to the end of defaults to have config.yaml override values set in other yamls

# add global default parameter values below
dataset:
  # whether to save intermediate steps
  save_intermediate: True
  # which data to include in the pre-processing/analysis
  dim: '2d' # '3d', 'both'
