# raw_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests/train/0_raw'
# raw_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests_small/train/0_raw'
# raw_dir: '/home/sebalzer/Documents/Mike_init/tests/train/0_raw'
raw_dir: '/home/sebalzer/Documents/Mike_init/tests_small/train/0_raw'
# out_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests/train'
# out_dir: '/mnt/c/Users/Sebastian/OneDrive/Dokumente/Insel/tests_small/train'
# out_dir: '/home/sebalzer/Documents/Mike_init/tests/train/'
out_dir: '/home/sebalzer/Documents/Mike_init/tests_small/train/'